[zlib] Fix gcc parenthesis warning in crc_folding.c from V8 roll
V8 roll uses gcc and [-Werror=parentheses], and started reporting code
errors in crc_folding.c recently, issue 1076360

  third_party/zlib/crc_folding.c:288:19: error: suggest parentheses
  around ‘-’ in operand of ‘&’ [-Werror=parentheses]
  288 |     algn_diff = 0 - (uintptr_t)src & 0xF;
      |                 ~~^~~~~~~~~~~~~~~~
  cc1: all warnings being treated as errors

Operator - has higher precedence than &, per C rules but help gcc work
out that that is the code intent by bracketing the expression:

  algn_diff = (0 - (uintptr_t)src) & 0xF;

[-Werror=parentheses] is happy with that change, and so is zlib_bench,
at zlib@1,3,6,9. No change in behavior: covered by many, many existing
integration, unit and blink layout tests.

Tbr: cblume, cavalcantii
Bug: 1076360, 1072308
Change-Id: Id9411dc96b638ca44ca9c67f6c411bf7c4bec519
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2172191
Reviewed-by: Noel Gordon <noel@chromium.org>
Reviewed-by: Michael Achenbach <machenbach@chromium.org>
Commit-Queue: Noel Gordon <noel@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#763787}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 7453f9f2d7adcdb5c30aa9d802d0a19d6c085bb7